/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsCarIdRouteImport } from './routes/cars.$carId'
import { Route as DealersIndexRouteImport } from './routes/dealers.index'
import { Route as DealersDealerIdRouteImport } from './routes/dealers.$dealerId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersIndexRoute = DealersIndexRouteImport.update({
  id: '/dealers/',
  path: '/dealers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealersDealerIdRoute = DealersDealerIdRouteImport.update({
  id: '/dealers/$dealerId',
  path: '/dealers/$dealerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/finance': typeof FinanceRoute
  '/insurance': typeof InsuranceRoute
  '/profile': typeof ProfileRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
  '/cars/': typeof CarsIndexRoute
  '/dealers/': typeof DealersIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/finance': typeof FinanceRoute
  '/insurance': typeof InsuranceRoute
  '/profile': typeof ProfileRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
  '/cars': typeof CarsIndexRoute
  '/dealers': typeof DealersIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/credit': typeof CreditRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/finance': typeof FinanceRoute
  '/insurance': typeof InsuranceRoute
  '/profile': typeof ProfileRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/dealers/$dealerId': typeof DealersDealerIdRoute
  '/cars/': typeof CarsIndexRoute
  '/dealers/': typeof DealersIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-chat'
    | '/auth'
    | '/chat'
    | '/compare'
    | '/credit'
    | '/dashboard'
    | '/delivery'
    | '/finance'
    | '/insurance'
    | '/profile'
    | '/api/ai-chat'
    | '/cars/$carId'
    | '/dealers/$dealerId'
    | '/cars/'
    | '/dealers/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-chat'
    | '/auth'
    | '/chat'
    | '/compare'
    | '/credit'
    | '/dashboard'
    | '/delivery'
    | '/finance'
    | '/insurance'
    | '/profile'
    | '/api/ai-chat'
    | '/cars/$carId'
    | '/dealers/$dealerId'
    | '/cars'
    | '/dealers'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-chat'
    | '/auth'
    | '/chat'
    | '/compare'
    | '/credit'
    | '/dashboard'
    | '/delivery'
    | '/finance'
    | '/insurance'
    | '/profile'
    | '/api/ai-chat'
    | '/cars/$carId'
    | '/dealers/$dealerId'
    | '/cars/'
    | '/dealers/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  CreditRoute: typeof CreditRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  FinanceRoute: typeof FinanceRoute
  InsuranceRoute: typeof InsuranceRoute
  ProfileRoute: typeof ProfileRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  CarsCarIdRoute: typeof CarsCarIdRoute
  DealersDealerIdRoute: typeof DealersDealerIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
  DealersIndexRoute: typeof DealersIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers/': {
      id: '/dealers/'
      path: '/dealers'
      fullPath: '/dealers/'
      preLoaderRoute: typeof DealersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealers/$dealerId': {
      id: '/dealers/$dealerId'
      path: '/dealers/$dealerId'
      fullPath: '/dealers/$dealerId'
      preLoaderRoute: typeof DealersDealerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  CreditRoute: CreditRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  FinanceRoute: FinanceRoute,
  InsuranceRoute: InsuranceRoute,
  ProfileRoute: ProfileRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  CarsCarIdRoute: CarsCarIdRoute,
  DealersDealerIdRoute: DealersDealerIdRoute,
  CarsIndexRoute: CarsIndexRoute,
  DealersIndexRoute: DealersIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
