/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsIndexRouteImport } from './routes/cars.index'
import { Route as CarsCarIdRouteImport } from './routes/cars.$carId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/': typeof CarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars': typeof CarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/': typeof CarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cars/$carId' | '/cars/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars/$carId' | '/cars'
  id: '__root__' | '/' | '/cars/$carId' | '/cars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsCarIdRoute: typeof CarsCarIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsCarIdRoute: CarsCarIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
